"""empty message

Revision ID: 04b887eb944d
Revises: 7e5ba524ee4b
Create Date: 2024-11-02 16:22:37.930622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b887eb944d'
down_revision = '7e5ba524ee4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('talent_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('talent_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('talent_description')
        batch_op.drop_column('talent_required')
        batch_op.drop_column('genres')
        batch_op.drop_column('web_link')

    # ### end Alembic commands ###
