"""empty message

Revision ID: 64820137c071
Revises: e593c6d0eecf
Create Date: 2024-11-05 21:10:38.252895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64820137c071'
down_revision = 'e593c6d0eecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))
        batch_op.alter_column('genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
        batch_op.drop_column('venue_description')
        batch_op.drop_column('venue_required')
        batch_op.drop_column('web_link')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))
        batch_op.alter_column('genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
        batch_op.drop_column('web_link')
        batch_op.drop_column('talent_description')
        batch_op.drop_column('talent_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('talent_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('web_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('venue_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('venue_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('genres',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
