"""empty message

Revision ID: c9138a1d218f
Revises: 04b887eb944d
Create Date: 2024-11-02 16:23:54.487524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9138a1d218f'
down_revision = '04b887eb944d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('venue_required', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('venue_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('venue_description')
        batch_op.drop_column('venue_required')
        batch_op.drop_column('web_link')

    # ### end Alembic commands ###
