"""empty message

Revision ID: e593c6d0eecf
Revises: c8086e469238
Create Date: 2024-11-05 15:12:48.052860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision = 'e593c6d0eecf'
down_revision = 'c8086e469238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Artist',  # Name of the table
        'genres',  # Name of the column to change
        type_=ARRAY(sa.String),  # New type for the column
        postgresql_using='genres::text[]'
    )
    op.alter_column(
        'Venue',  # Name of the table
        'genres',  # Name of the column to change
        type_=ARRAY(sa.String),  # New type for the column
        postgresql_using='genres::text[]'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
